name: light
description: Plugin for the light sensor (Android only)
version: 2.1.0
homepage: https://github.com/cph-cachet/flutter-plugins/tree/master

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
#  flutter_test:
#    sdk: flutter

flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: dk.cachet.light
        pluginClass: LightPlugin
      ios:
        pluginClass: LightPlugin

