name: audio_streamer
description: Streaming of Pulse-code modulation (PCM) audio from Android and iOS
version: 2.0.3
homepage: https://github.com/cph-cachet/flutter-plugins/tree/master/packages/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  permission_handler: ^8.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: plugins.cachet.audio_streamer
        pluginClass: AudioStreamerPlugin
      ios:
        pluginClass: SwiftAudioStreamerPlugin
